variables:
  NVIM_SCALA_LOG_FILE: "/tmp/nvimhost_scala_log.txt"
  NVIM_LISTEN_ADDRESS: "127.0.0.1:7777"

stages:
- build
- test

image: registry.gitlab.com/viniarck/nvimhost-scala:test

scala212-build:
  stage: build
  script:
    - sbt publishLocal
    - ls ~/.ivy2/local/io.github.viniarck/nvimhost-scala_2.12/
    - cd src/test/
    - sbt assembly
    - ls target/scala-2.12/
    - ls ~
  only:
    changes:
      - src/**/*
      - system_tests/**/*
  artifacts:
    paths:
     - ./src/test/target/scala-2.12/

scala212-systemtests:
  stage: test
  only:
    changes:
      - src/**/*
      - system_tests/**
  script:
    - nvim --version
    - cp ./src/test/target/scala-2.12/demoplugin.jar ~/demoplugin.jar
    - ls -lar ~/demoplugin.jar
    - echo $NVIM_LISTEN_ADDRESS
    - echo $NVIM_SCALA_LOG_FILE
    - echo $PATH
    - pip3 install -r requirements-dev.txt
    - python3 -m pytest -s -vv system_tests/test_demo_plugin_bootstrap.py --tb=short
    - cat ~/demoplugin.vim
    - python3 -m pytest -s -vv system_tests/test_demo_plugin_functions.py --tb=short
